version: '3.8'

services:
  lumen:
    image: php:8.2-fpm
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ["composer"]

  artisan:
    image: php:8.2-cli
    container_name: artisan
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ["php", "/var/www/artisan"]